padron/api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('localidades/', views.localidad_list),
    path('localidades/<int:pk>/', views.localidad_detail),
]

padron/padron/urls.py
from django.contrib import admin
from django.urls import path, include
from hola.views import hola_func
from usuarios.views import PaginaPrincipal
from django.conf import settings
from django.conf.urls.static import static


from rest_framework.authtoken import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hola/', hola_func),
    path('usuarios/', include('usuarios.urls')),
    path('localidades/', include('usuarios.urls_loc')),
    path('inmuebles/', include('inmuebles.urls')),
    
    path('', PaginaPrincipal.as_view(), name='principal'),
    
    
    path('api/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    
    # path('api-token-auth/', views.obtain_auth_token),
    
    path('api/auth/', include('knox.urls'))
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# jiapaz.gob.mx/usuarios
# jiapaz.gob.mx/usuarios/nuevo
# jiapaz.gob.mx/usuarios/eliminar/1
# jiapaz.gob.mx/usuarios/lista

# jiapaz.gob.mx/localidades
# jiapaz.gob.mx/localidades/nuevo
# jiapaz.gob.mx/localidades/eliminar/1
# jiapaz.gob.mx/localidades/editar/1

# jiapaz.gob.mx/hola

padron/usuarios/urls.py
from django.urls import path
from usuarios import views
from django.contrib.auth.views import LogoutView


urlpatterns = [
    path('', views.lista_usuarios, name='lista_usuarios'),
    path('nuevo', views.nuevo_usuario, name='nuevo_usuario'),
    path('eliminar/<int:id>', views.eliminar_usuario, name='eliminar_usuario'),
    path('editar/<int:id>', views.editar_usuario, name='editar_usuario'),
    path('datalle/<int:id>', views.ver_usuario, name='ver_usuario'),
    
    path('login', views.EntrarView.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    
    path('asigna-grupo', views.asigna_grupos, name='asigna_grupos'),
    
]


# jiapaz.gob.mx/usuarios
# jiapaz.gob.mx/usuarios/nuevo
# jiapaz.gob.mx/usuarios/eliminar/1
# jiapaz.gob.mx/usuarios/
# jiapaz.gob.mx/hola

padron/usuarios/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinLengthValidator
from usuarios.validators import curp_validator


EDO_CIVIL = (
    ('', '-------'),
    ('1', 'Soltero(a)'),
    ('2', 'Casado(a)'),
    ('3', 'Divorciado(a)'),
    ('4', 'Viudo(a)'),
)

GENERO = (
    ('', '-------'),
    ('1', 'Femenino'),
    ('2', 'Masculino'),
    ('3', 'No binario'),
)

class Usuario(models.Model):
    curp = models.CharField('CURP', max_length=18, 
        validators=[
            MinLengthValidator(16, 'La longitud minima es de 16 caracteres'),
            curp_validator
        ]
    )
    inmueble = models.BigIntegerField()
    derivada = models.BigIntegerField()
    toma = models.SmallIntegerField()
    nombre = models.CharField(max_length=100)
    apellido_materno = models.CharField(max_length=100)
    apellido_paterno = models.CharField(max_length=100)
    localidad = models.ForeignKey("usuarios.Localidad", verbose_name='Localidad', on_delete=models.DO_NOTHING)
    estado_civil = models.CharField('Estado civil', max_length=1, choices=EDO_CIVIL)
    genero = models.CharField('Sexo', max_length=1, choices=GENERO)
    colonia = models.ForeignKey("usuarios.Colonia", verbose_name="Colonia", on_delete=models.DO_NOTHING)
    user = models.OneToOneField(User, verbose_name="Usuario", related_name='usuario_user', on_delete=models.CASCADE)
    foto = models.ImageField(upload_to='perfiles',null=True, blank=True)
    archivo = models.FileField(upload_to='archivos',null=True, blank=True )
    
    def __str__(self):
        return f"{self.nombre} {self.apellido_paterno} {self.apellido_materno}" 
    
class Localidad(models.Model):
    nombre = models.CharField(max_length=200)
    descripcion = models.TextField('Descripción', null=True, blank=True)
    
    def __str__(self):
        return self.nombre
    
class Colonia(models.Model):
    nombre = models.CharField(max_length=200)
    localidad = models.ForeignKey("usuarios.Localidad", verbose_name="Localidad", on_delete=models.CASCADE)
    
    def __str__(self):
        return self.nombre

padron/usuarios/forms.py
from django import forms
from usuarios.models import Usuario, Localidad, EDO_CIVIL, GENERO
from django.contrib.auth.models import User


class FormUsuario(forms.ModelForm):
    
    class Meta:
        model = Usuario
        fields = [
            'derivada', 
            'inmueble', 
            'toma', 
            'nombre',
            'apellido_paterno',
            'apellido_materno',
            'curp',
            'localidad',
            'colonia',
            'estado_civil',
            'genero',
            'foto',
            'archivo',
        ]
        # fields = '__all__'
        # exclude = ['toma','inmueble']
        
        widgets = {
            'inmueble':forms.NumberInput(attrs={'class':'form-control'}),
            'derivada':forms.NumberInput(attrs={'class':'form-control'}),
            'toma':forms.NumberInput(attrs={'class':'form-control'}),
            'nombre':forms.TextInput(attrs={'class':'form-control'}),
            'apellido_paterno':forms.TextInput(attrs={'class':'form-control'}),
            'apellido_materno':forms.TextInput(attrs={'class':'form-control'}),
            'curp':forms.TextInput(attrs={'class':'form-control'}),
            'localidad':forms.Select(attrs={'class':'form-control'}),
            'colonia':forms.Select(attrs={'class':'form-control'}),
            'estado_civil':forms.Select(attrs={'class':'form-control'}),
            'genero':forms.Select(attrs={'class':'form-control'}),
        }
        
class FormUser(forms.ModelForm):
    username = forms.CharField(label='Número de empleado', 
        widget=forms.TextInput(attrs={'class':'form-control'}))
    class Meta:
        model = User
        fields = ['username','email']
        widgets = {
            'email':forms.EmailInput(attrs={'class':'form-control'}),
        }
        
    
class FormLocalidad(forms.ModelForm):
    
    class Meta:
        model = Localidad
        fields = '__all__'
        widgets = {
            'nombre':forms.TextInput(attrs={'class':'form-control','placeholder':'Escribe tu nombre'}),
            'descripcion':forms.Textarea(attrs={'class':'form-control'}),
        }
        
class FormBusqueda(forms.Form):
    nombre = forms.CharField(
        max_length=100, 
        required=False, 
        widget=forms.TextInput(attrs={'placeholder':'Nombre','class':'form-control'})
    )
    apellido_paterno = forms.CharField(
        max_length=100, 
        required=False,
        widget=forms.TextInput(attrs={'placeholder':'Apellido paterno','class':'form-control'})
    )
    apellido_materno = forms.CharField(
        max_length=100, 
        required=False,
        widget=forms.TextInput(attrs={'placeholder':'Apellido materno','class':'form-control'})
    )
    genero = forms.CharField(
        max_length=1, 
        required=False, 
        widget=forms.Select(choices=GENERO, attrs={'class':'form-control'})
    )
    estado_civil = forms.CharField(
        max_length=1, 
        required=False, 
        widget=forms.Select(choices=EDO_CIVIL, attrs={'class':'form-control'})
    )
    localidad = forms.CharField(
        max_length=100, 
        required=False, 
        widget=forms.TextInput(attrs={'placeholder':'Localidad','class':'form-control'})
    )
    
    

padron/usuarios/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from usuarios.models import Usuario
from usuarios.forms import FormUsuario, FormBusqueda, FormUser
from django.contrib import messages
from django.contrib.auth.decorators import permission_required, login_required
from django.contrib.auth.views import LoginView
from django.contrib.auth.forms import AuthenticationForm
from django.views.generic import TemplateView
from django.contrib.auth.models import Group, User


class EntrarView(LoginView):
    template_name = 'login.html'
    form_class = AuthenticationForm

class PaginaPrincipal(TemplateView):
    template_name = 'principal.html'

@login_required()
def lista_usuarios(request):
    # usuarios = Usuario.objects.all()
    # select * from usuario;
    
    # usuarios = Usuario.objects.all().values('nombre','id')
    grupos = Group.objects.all()
    usuarios = Usuario.objects.all().order_by('nombre','apellido_materno')
    form = FormBusqueda()
    if request.method == 'POST':
        form = FormBusqueda(request.POST)
        nombre = request.POST.get('nombre', None)
        apellido_paterno = request.POST.get('apellido_paterno', None)
        apellido_materno = request.POST.get('apellido_materno', None)
        genero = request.POST.get('genero', None)
        estado_civil = request.POST.get('estado_civil', None)
        localidad = request.POST.get('localidad', None)
        if nombre:
            usuarios = usuarios.filter(nombre=nombre)
        if apellido_paterno:
            usuarios = usuarios.filter(apellido_paterno=apellido_paterno)
        if apellido_materno:
            usuarios = usuarios.filter(apellido_materno=apellido_materno)
        if genero:
            usuarios = usuarios.filter(genero=genero)
        if estado_civil:
            usuarios = usuarios.filter(estado_civil=estado_civil)
        if localidad:
            usuarios = usuarios.filter(localidad__nombre__contains=localidad)
    
    paginator = Paginator(usuarios, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
        
    print(page_obj)
    context = {
        # 'usuarios': Usuario.objects.filter(nombre__exact='jUan') #case-sensitive
        # 'usuarios': Usuario.objects.filter(nombre__iexact='jUan') #no case-sensitive
        # 'usuarios': Usuario.objects.filter(nombre__startswith='J') #no case-sensitive
        # 'usuarios': Usuario.objects.filter(nombre__endswith='n') #no case-sensitive
        # 'usuarios': Usuario.objects.filter(nombre__contains='a') #no case-sensitive
        # 'usuarios': Usuario.objects.filter(nombre__contains='a', apellido_paterno__contains='au'), #no case-sensitive
        'usuarios': page_obj,
        'form': form,
        'grupos': grupos
    }
    
    return render(request, 'usuarios.html', context)

@permission_required('usuarios.add_usuario')
def nuevo_usuario(request):
    if request.method == 'POST':
        form = FormUsuario(request.POST, prefix='usuario', files=request.FILES)
        form_user = FormUser(request.POST, prefix='user')
        if form_user.is_valid() and form.is_valid():
            user = form_user.save(commit=False)
            user.set_password('Temporal123') 
            user.save()
            
            usuario = form.save(commit=False)
            usuario.user = user
            usuario.save()
            
            messages.success(request, f"El usuario {usuario.nombre} se guardo con éxito")
            return redirect('lista_usuarios')
        else:
            messages.error(request, 'Ocurrió un error al guardar el usuario; revisa tu información')
            
    else:
        form = FormUsuario(prefix='usuario')
        form_user = FormUser(prefix='user')
    
    context = {
        'form': form,
        'form_user': form_user
    }
    
    return render(request, 'nuevo_usuario.html', context)

@permission_required('usuarios.todo_usuarios')
def editar_usuario(request, id):
    usuario = Usuario.objects.get(id=id)
    if request.method == 'POST':
        form = FormUsuario(request.POST, instance=usuario, files=request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, f"El usuario {usuario.nombre} se guardó con éxito")
            return redirect('lista_usuarios')
        else:
            messages.error(request, 'Ocurrió un error al guardar el usuario; revisa tu información')
            
    else:
        form = FormUsuario(instance=usuario)
        
    return render(request, 'nuevo_usuario.html', {'form':form, 'editar':True}) 


def eliminar_usuario(request, id):
    try:
        Usuario.objects.get(id=id).delete()
        messages.success(request, f"El usuario se eliminó con éxito")
    except:
        messages.error(request, 'Ocurrió un error al eliminar el usuario')
      
    return redirect('lista_usuarios')
    
def ver_usuario(request, id):
    usuario = Usuario.objects.get(id=id)
    return render(request, 'detalle_usuario.html', {'usuario':usuario})

def asigna_grupos(request):
    # print (request.POST)
    try:
        id_grupo = int(request.POST.get('grupos',0))
        grupo = Group.objects.get(id=id_grupo)
        for item in request.POST:
            if request.POST[item] == 'on':
                usuario = User.objects.get(id=int(item))
                usuario.groups.add(grupo)
        messages.success(request, f"Se asignaron los usuarios al grupo {grupo.name}")
    except:
        messages.error(request, "Ocurrió un error al asignar los usuarios al grupo")
    return redirect('lista_usuarios')

padron/usuarios/templates/detalle_usuario.html
{% extends 'base.html' %}

{% block titulo %}
  Detalle de usuario
{% endblock titulo %}

{% block contenido %}
  
    <h1>Detalle usuario</h1>
    <hr>
    <br>
    <p>Inmueble: <b>{{usuario.inmueble}}</b></p>
    <p>Derivada: <b>{{usuario.derivada}}</b></p>
    <p>Toma: <b>{{usuario.toma}}</b></p>

    <p>Nombre: <b>{{usuario.nombre}} {{usuario.apellido_paterno}} {{usuario.apellido_materno}}</b></p>
    <p>Estado civil: <b>{{usuario.get_estado_civil_display}}</b></p>
    <p>Genero: <b>{{usuario.get_genero_display}}</b></p>
    <p>Localidad: <b>{{usuario.localidad}}</b></p>
    <p>Localidad descripción: <b>{{usuario.localidad.descripcion}}</b></p>
    <hr>
    <h5>Grupos:</h5>
    <ul>
      {% for grupo in usuario.user.groups.all %}
        <li>{{grupo.name|upper}}</li>
      {% endfor %}
    </ul>

    <img width="300px" src="{{ MEDIA_URL }}{{usuario.foto}}" alt="">
    <a href="{{ MEDIA_URL }}{{usuario.archivo}}" 
      target="_blank" >
      Archivo
    </a>

    <a href="{% url 'lista_usuarios' %}">Regresar</a>
{% endblock contenido %}

padron/usuarios/templates/editar_usuario.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Actualizar usuario</title>
</head>
<body>
    <h1>Actualizar usuario</h1>
    <ul>
        <form method="post">
            {% csrf_token %}
            {{form.as_ul}}
            <input type="submit" value="Guardar">
            <a href="{% url 'lista_usuarios' %}">Cancelar</a>
        </form>
    </ul>
</body>
</html>

padron/usuarios/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="apple-touch-icon" sizes="76x76" href="{% static '/assets/img/apple-icon.png' %}">
  <link rel="icon" type="image/png" href="{% static '/assets/img/favicon.png' %}">
  <title>
    Soft UI Dashboard by Creative Tim
  </title>
  <!--     Fonts and icons     -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet" />
  <!-- Nucleo Icons -->
  <link href="{% static '/assets/css/nucleo-icons.css' %}" rel="stylesheet" />
  <link href="{% static '/assets/css/nucleo-svg.css' %}" rel="stylesheet" />
  <!-- Font Awesome Icons -->
  <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
  <link href="{% static '/assets/css/nucleo-svg.css' %}" rel="stylesheet" />
  <!-- CSS Files -->
  <link id="pagestyle" href="{% static '/assets/css/soft-ui-dashboard.css' %}" rel="stylesheet" />
</head>

<body class="">
  <div class="container position-sticky z-index-sticky top-0">
    <div class="row">
      <div class="col-12">
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg blur blur-rounded top-0 z-index-3 shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
          <div class="container-fluid pe-0">
            <a class="navbar-brand font-weight-bolder ms-lg-0 ms-3 " href="../pages/dashboard.html">
              Soft UI Dashboard
            </a>
            <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon mt-2">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </span>
            </button>
            <div class="collapse navbar-collapse" id="navigation">
              <ul class="navbar-nav mx-auto ms-xl-auto me-xl-7">
                <li class="nav-item">
                  <a class="nav-link d-flex align-items-center me-2 active" aria-current="page" href="../pages/dashboard.html">
                    <i class="fa fa-chart-pie opacity-6 text-dark me-1"></i>
                    Dashboard
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link me-2" href="../pages/profile.html">
                    <i class="fa fa-user opacity-6 text-dark me-1"></i>
                    Profile
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link me-2" href="../pages/sign-up.html">
                    <i class="fas fa-user-circle opacity-6 text-dark me-1"></i>
                    Sign Up
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link me-2" href="../pages/sign-in.html">
                    <i class="fas fa-key opacity-6 text-dark me-1"></i>
                    Sign In
                  </a>
                </li>
              </ul>
              <li class="nav-item d-flex align-items-center">
                <a class="btn btn-round btn-sm mb-0 btn-outline-primary me-2" target="_blank" href="https://www.creative-tim.com/builder/soft-ui?ref=navbar-dashboard">Online Builder</a>
              </li>
              <ul class="navbar-nav d-lg-block d-none">
                <li class="nav-item">
                  <a href="https://www.creative-tim.com/product/soft-ui-dashboard" class="btn btn-sm btn-round mb-0 me-1 bg-gradient-dark">Free download</a>
                </li>
              </ul>
            </div>
          </div>
        </nav>
        <!-- End Navbar -->
      </div>
    </div>
  </div>
  <main class="main-content  mt-0">
    <section>
      <div class="page-header min-vh-75">
        <div class="container">
          <div class="row">
            <div class="col-xl-4 col-lg-5 col-md-6 d-flex flex-column mx-auto">
              <div class="card card-plain mt-8">
                <div class="card-header pb-0 text-left bg-transparent">
                  <h3 class="font-weight-bolder text-info text-gradient">Welcome back</h3>
                  <p class="mb-0">Enter your email and password to sign in</p>
                </div>
                
                {% if form.errors %}
                    <div class="alert alert-warning">
                        <p>Verifica tus credenciales; el usuario no existe</p>                    
                    </div>
                {% endif %}
                    
                <div class="card-body">
                  <form role="form" method="post">
                    {% csrf_token %}
                    <label>Username</label>
                    <div class="mb-3">
                      <input type="text" name="username" class="form-control" placeholder="Username" aria-label="Email" aria-describedby="email-addon">
                    </div>
                    <label>Password</label>
                    <div class="mb-3">
                      <input type="password" name="password" class="form-control" placeholder="Password" aria-label="Password" aria-describedby="password-addon">
                    </div>
                    <div class="form-check form-switch">
                      <input class="form-check-input" type="checkbox" id="rememberMe" checked="">
                      <label class="form-check-label" for="rememberMe">Remember me</label>
                    </div>
                    <div class="text-center">
                      <button type="submit" class="btn bg-gradient-info w-100 mt-4 mb-0">Sign in</button>
                    </div>
                    <input type="hidden" name="next" value="{{next}}">
                  </form>
                </div>
                <div class="card-footer text-center pt-0 px-lg-2 px-1">
                  <p class="mb-4 text-sm mx-auto">
                    Don't have an account?
                    <a href="javascript:;" class="text-info text-gradient font-weight-bold">Sign up</a>
                  </p>
                </div>
              </div>
            </div>
            <div class="col-md-6">
              <div class="oblique position-absolute top-0 h-100 d-md-block d-none me-n8">
                <div class="oblique-image bg-cover position-absolute fixed-top ms-auto h-100 z-index-0 ms-n6" style="background-image:url('{% static 'assets/img/curved-images/curved6.jpg' %}')"></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </main>
  <!-- -------- START FOOTER 3 w/ COMPANY DESCRIPTION WITH LINKS & SOCIAL ICONS & COPYRIGHT ------- -->
  <footer class="footer py-5">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 mb-4 mx-auto text-center">
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
            Company
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
            About Us
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
            Team
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
            Products
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
            Blog
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
            Pricing
          </a>
        </div>
        <div class="col-lg-8 mx-auto text-center mb-4 mt-2">
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-4 me-4">
            <span class="text-lg fab fa-dribbble"></span>
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-4 me-4">
            <span class="text-lg fab fa-twitter"></span>
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-4 me-4">
            <span class="text-lg fab fa-instagram"></span>
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-4 me-4">
            <span class="text-lg fab fa-pinterest"></span>
          </a>
          <a href="javascript:;" target="_blank" class="text-secondary me-xl-4 me-4">
            <span class="text-lg fab fa-github"></span>
          </a>
        </div>
      </div>
      <div class="row">
        <div class="col-8 mx-auto text-center mt-1">
          <p class="mb-0 text-secondary">
            Copyright © <script>
              document.write(new Date().getFullYear())
            </script> Soft by Creative Tim.
          </p>
        </div>
      </div>
    </div>
  </footer>
  <!-- -------- END FOOTER 3 w/ COMPANY DESCRIPTION WITH LINKS & SOCIAL ICONS & COPYRIGHT ------- -->
  <!--   Core JS Files   -->
  <script src="{% static '/assets/js/core/popper.min.js' %}"></script>
  <script src="{% static '/assets/js/core/bootstrap.min.js' %}"></script>
  <script src="{% static '/assets/js/plugins/perfect-scrollbar.min.js' %}"></script>
  <script src="{% static '/assets/js/plugins/smooth-scrollbar.min.js' %}"></script>
  <script>
    var win = navigator.platform.indexOf('Win') > -1;
    if (win && document.querySelector('#sidenav-scrollbar')) {
      var options = {
        damping: '0.5'
      }
      Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
    }
  </script>
  <!-- Github buttons -->
  <script async defer src="https://buttons.github.io/buttons.js"></script>
  <!-- Control Center for Soft Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="{% static '/assets/js/soft-ui-dashboard.min.js' %}"></script>
</body>

</html>

padron/usuarios/templates/usuarios.html
{% extends 'base.html' %}

{% block titulo %}
    Lista de usuarios
{% endblock titulo %}

{% block contenido %}

    <h1>Lista de usuarios</h1>
    {% include "mensajes.html" %}
    <a class="btn btn-success" href="{% url 'nuevo_usuario' %}">Nuevo</a>
    <form method="post">
        {% csrf_token %}
        
        <table>
            <tr>
                <td>{{form.nombre}}</td>
                <td>{{form.apellido_paterno}}</td>
                <td>{{form.apellido_materno}}</td>
                <td>{{form.genero}}</td>
                <td>{{form.estado_civil}}</td>
                <td>{{form.localidad}}</td>
                <td>
                    <input class="btn btn-primary" type="submit" value="Buscar">
                </td>
            </tr>
        </table>
    </form>
    <div class="row">
        <div class="col-6">
            <form method="post" action="{% url 'asigna_grupos' %}">
                {% csrf_token %}
                <select name="grupos" class="form-select">
                    {% for grupo in grupos %}
                        <option value="{{grupo.id}}">{{grupo.name}}</option>
                    {% endfor %}
                </select>
        </div>
        <div class="col-6">
            <button class="btn btn-sm btn-success" type="submit">Asignar grupo</button>
        </div>
        </div>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th></th>
                <th>Inmueble</th>
                <th>Derivada</th>
                <th>Toma</th>
                <th>Nombre</th>
                <th>Localidad</th>
                <th>Estado civil</th>
                <th>Genero</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for usuario in usuarios %}
              <tr>
                <td> 
                    <input type="checkbox" name="{{usuario.id}}"> 
                </td>
                <td>{{usuario.inmueble}}</td>
                <td>{{usuario.derivada}}</td>
                <td>{{usuario.toma}}</td>
                <td>{{usuario.nombre}} {{usuario.apellido_paterno}} {{usuario.apellido_materno}} </td>
                <td>{{usuario.localidad}}</td>
                <td>{{usuario.get_estado_civil_display}}</td>
                <td>{{usuario.get_genero_display}}</td>
                <td>
                    <a class="btn btn-sm btn-danger" href="{% url 'eliminar_usuario' usuario.id %}">Eliminar</a>
                    <a class="btn btn-sm btn-primary" href="{% url 'editar_usuario' usuario.id %}">Editar</a>
                    <a class="btn btn-sm btn-warning" href="{% url 'ver_usuario' usuario.id %}">Detalle</a>
                </td>
              </tr>
            {% endfor %}
        </tbody>
    </form> {% comment %}cierra form para grupos   {% endcomment %}
    </table>
    <div class="pagination">
        <span class="step-links">
            {% if usuarios.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ usuarios.previous_page_number }}">previous</a>
            {% endif %}
    
            <span class="current">
                Page {{ usuarios.number }} of {{ usuarios.paginator.num_pages }}.
            </span>
    
            {% if usuarios.has_next %}
                <a href="?page={{ usuarios.next_page_number }}">next</a>
                <a href="?page={{ usuarios.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
{% endblock contenido %}